export enum Environment {
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',
  AWS_REGION = 'AWS_REGION',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  RABBITMQ_USER = 'RABBITMQ_USER',
  RABBITMQ_PASSWORD = 'RABBITMQ_PASSWORD',
  RABBITMQ_HOST = 'RABBITMQ_HOST',
  RABBITMQ_QUEUE_ADMIN = 'RABBITMQ_QUEUE_ADMIN',
  RABBITMQ_QUEUE_CHALLENGES = 'RABBITMQ_QUEUE_CHALLENGES',
}